import type { Candidate } from "./types"

export const candidates: Candidate[] = [
  {
    id: "1",
    name: "Alex Johnson",
    email: "alex.johnson@example.com",
    phone: "(555) 123-4567",
    location: "San Francisco, CA",
    submitted_at: "2023-05-15T14:30:00Z",
    work_availability: ["Full-time", "Remote"],
    annual_salary_expectation: { amount: 120000, currency: "USD" },
    skills: ["React", "TypeScript", "CSS", "Next.js"],
    title: "Senior Frontend Developer",
    experience: 5,
    education: {
      highest_level: "Bachelor's",
      degrees: [
        {
          degree: "BS",
          subject: "Computer Science",
          school: "Stanford University",
          gpa: 3.8,
          startDate: "2014-09-01",
          endDate: "2018-05-30",
          originalSchool: "Stanford University",
          isTop50: true,
        },
      ],
    },
    avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "2",
    name: "Sarah Williams",
    email: "sarah.williams@example.com",
    phone: "(555) 987-6543",
    location: "New York, NY",
    submitted_at: "2023-05-10T09:15:00Z",
    work_availability: ["Full-time", "On-site"],
    annual_salary_expectation: { amount: 95000, currency: "USD" },
    skills: ["Figma", "Adobe XD", "Sketch", "User Research"],
    title: "UX/UI Designer",
    experience: 4,
    education: {
      highest_level: "Bachelor's",
      degrees: [
        {
          degree: "BFA",
          subject: "Design",
          school: "Rhode Island School of Design",
          gpa: 3.9,
          startDate: "2015-09-01",
          endDate: "2019-05-30",
          originalSchool: "Rhode Island School of Design",
          isTop50: true,
        },
      ],
    },
    avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "3",
    name: "Michael Chen",
    email: "michael.chen@example.com",
    phone: "(555) 456-7890",
    location: "Austin, TX",
    submitted_at: "2023-05-12T11:45:00Z",
    work_availability: ["Full-time", "Hybrid"],
    annual_salary_expectation: { amount: 140000, currency: "USD" },
    skills: ["Node.js", "React", "MongoDB", "AWS"],
    title: "Full Stack Engineer",
    experience: 7,
    education: {
      highest_level: "Master's",
      degrees: [
        {
          degree: "MS",
          subject: "Computer Engineering",
          school: "MIT",
          gpa: 4.0,
          startDate: "2012-09-01",
          endDate: "2014-05-30",
          originalSchool: "MIT",
          isTop50: true,
        },
        {
          degree: "BS",
          subject: "Computer Science",
          school: "UC Berkeley",
          gpa: 3.7,
          startDate: "2008-09-01",
          endDate: "2012-05-30",
          originalSchool: "UC Berkeley",
          isTop50: true,
        },
      ],
    },
    avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "4",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@example.com",
    phone: "(555) 789-0123",
    location: "Seattle, WA",
    submitted_at: "2023-05-08T16:20:00Z",
    work_availability: ["Full-time", "On-site"],
    annual_salary_expectation: { amount: 130000, currency: "USD" },
    skills: ["Agile", "Roadmapping", "User Stories", "Analytics"],
    title: "Product Manager",
    experience: 6,
    education: {
      highest_level: "Master's",
      degrees: [
        {
          degree: "MBA",
          subject: "Business Administration",
          school: "Harvard Business School",
          gpa: 3.8,
          startDate: "2015-09-01",
          endDate: "2017-05-30",
          originalSchool: "Harvard Business School",
          isTop50: true,
        },
        {
          degree: "BA",
          subject: "Economics",
          school: "UCLA",
          gpa: 3.6,
          startDate: "2011-09-01",
          endDate: "2015-05-30",
          originalSchool: "UCLA",
          isTop50: true,
        },
      ],
    },
    avatar: "/placeholder.svg?height=100&width=100",
  },
]
